// Generated by CoffeeScript 1.4.0
(function() {
  var getPort, http, net, utils, weinre;

  net = require('net');

  utils = require("../util");

  weinre = require("weinre");

  http = require("http");

  exports.run = function(options) {
    return getPort(function(port) {
      var weinreOption;
      weinreOption = {
        httpPort: port,
        boundHost: '-all-',
        verbose: false,
        debug: false,
        readTimeout: 5
      };
      weinreOption.deathTimeout = 3 * weinreOption.readTimeout;
      weinre.run(weinreOption);
      process.env["WEINRE_PORT"]=port
      return utils.logger.log('weinre已启动');
    });
  };

  getPort = function(callback) {
    var port, server;
    server = http.createServer();
    server.listen(0);
    port = 0;
    server.on('listening', function() {
      port = server.address().port;
      return server.close();
    });
    return server.on('close', function() {
      return callback(port);
    });
  };

}).call(this);
